apiVersion: v1
kind: Service
metadata:
  name: hfcs
  namespace: hfcs
  labels:
    app: hfcs
    k8s-app: hfcs
spec:
  type: NodePort
  ports:
  - name: hfcs
    port: 3000
    protocol: TCP
    nodePort: 30005
  selector:
    app: hfcs

