apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hfcs
  namespace: hfcs
  labels:
    k8s-app: hfcs
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hfcs
  template:
    metadata:
      labels:
        k8s-app: hfcs
    spec:
      containers:
      - name: hfcs
        image: hfcs:latest
        imagePullPolicy: Never
        ports:
        - protocol: TCP
          containerPort: 3000
        volumeMounts:
        - name: crypto-config
          mountPath: /crypto-config
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
      - name: crypto-config
        hostPath:
          path: /var/fabric-net/crypto-config
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config

